# Generated by Django 6.0.1 on 2026-01-25 16:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='', upload_to='main_app/static/uploads')),
                ('bio', models.TextField()),
                ('age', models.IntegerField()),
                ('skin_type', models.CharField(choices=[('N', 'Normal'), ('D', 'Dry'), ('O', 'Oily'), ('C', 'Combination'), ('S', 'Sensitive')], default='N', max_length=15)),
                ('Skin_concern', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('R', 'Redness'), ('D', 'Dryness'), ('F', 'Fine Lines'), ('A', 'Acne'), ('S', 'Sensitivity'), ('T', 'Texture'), ('H', 'Darkspot')], max_length=20), default=list)),
                ('Avoided_ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('P', 'Parabens'), ('O', 'Oils'), ('F', 'Fragrance'), ('S', 'Sulfates'), ('A', 'Harsh Alcahols'), ('D', 'Silicons')], max_length=30), blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
