# Generated by Django 6.0.1 on 2026-01-25 17:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Skin_concern',
            new_name='skin_concern',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Avoided_ingredients',
        ),
        migrations.AddField(
            model_name='profile',
            name='avoided_ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('P', 'Parabens'), ('O', 'Oils'), ('F', 'Fragrance'), ('S', 'Sulfates'), ('A', 'Harsh Alcohols'), ('D', 'Silicones')], max_length=30), blank=True, default=list),
        ),
    ]
