# Generated by Django 6.0.1 on 2026-01-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_skin_concern_profile_skin_concern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('Image', models.ImageField(default='', upload_to='main_app/static/uploads')),
                ('description', models.TextField()),
                ('reading_time', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
