# Generated by Django 6.0.1 on 2026-01-29 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Image',
            new_name='image',
        ),
    ]
