# Generated by Django 6.0.1 on 2026-01-30 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_image_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_app/static/uploads')),
                ('product_id', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
