# Generated by Django 6.0.1 on 2026-02-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=3)),
                ('order', models.PositiveIntegerField()),
                ('time', models.CharField(choices=[('MORNING AND EVENING', 'Morning and evening'), ('MORNING', 'Morning'), ('EVENING', 'Evening')], default='MORNING AND EVENING', max_length=50)),
                ('frequency', models.CharField(choices=[('EVERY DAY', 'Every Day'), ('EVERY OTHER DAY', 'Every other day'), ('EVERY 3 DAYS', 'Every 3 days'), ('EVERY 4 DAYS', 'Every 4 days'), ('EVERY WEEK', 'Every week'), ('ON SPECIFIC DAYS', 'On specific days'), ('AS NEEDED', 'As needed')], default='EVERY DAY', max_length=50)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('steps', models.ManyToManyField(to='main_app.routinestep')),
            ],
        ),
    ]
