# Generated by Django 6.0.1 on 2026-02-07 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='steps',
        ),
        migrations.CreateModel(
            name='RoutineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=3)),
                ('order', models.PositiveIntegerField(default=0)),
                ('time', models.CharField(choices=[('MORNING AND EVENING', 'Morning and evening'), ('MORNING', 'Morning'), ('EVENING', 'Evening')], default='MORNING AND EVENING', max_length=50)),
                ('frequency', models.CharField(choices=[('EVERY DAY', 'Every Day'), ('EVERY OTHER DAY', 'Every other day'), ('EVERY 3 DAYS', 'Every 3 days'), ('EVERY 4 DAYS', 'Every 4 days'), ('EVERY WEEK', 'Every week'), ('ON SPECIFIC DAYS', 'On specific days'), ('AS NEEDED', 'As needed')], default='EVERY DAY', max_length=50)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.routine')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='RoutineStep',
        ),
    ]
