# Generated by Django 6.0.1 on 2026-02-07 19:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_routine_steps_routineproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avoided_ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PARABENS', 'Parabens'), ('OILS', 'Oils'), ('FRAGRANCE', 'Fragrance'), ('SULFATES', 'Sulfates'), ('HARSH ALCOHOLS', 'Harsh Alcohols'), ('SILICONES', 'Silicones')], max_length=30), blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skin_concern',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('REDNESS', 'Redness'), ('DRYNESS', 'Dryness'), ('FINE LINES', 'Fine Lines'), ('ACNE', 'Acne'), ('SENSITIVITY', 'Sensitivity'), ('TEXTURE', 'Texture'), ('DARKSPOT', 'Darkspot')], max_length=20), default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skin_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('DRY', 'Dry'), ('OILY', 'Oily'), ('COMBINATION', 'Combination'), ('SENSITIVE', 'Sensitive')], default='NORMAL', max_length=15),
        ),
    ]
