# Generated by Django 6.0.1 on 2026-02-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='https://i.postimg.cc/Z54tWZ5W/profile.png', upload_to='main_app/static/uploads'),
        ),
    ]
