# Generated by Django 6.0.1 on 2026-02-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='https://i.postimg.cc/Z54tWZ5W/profile.png', upload_to='main_app/static/uploads'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_app/static/uploads'),
        ),
    ]
