# Generated by Django 6.0.1 on 2026-02-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineproduct',
            name='order',
            field=models.PositiveIntegerField(default=100000),
        ),
    ]
